web/router.ex
defmodule Bookmarks.Router do
  use Bookmarks.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bookmarks.AuthPlug, repo: Bookmarks.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", Bookmarks do
    pipe_through :browser
    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end

  scope "/", Bookmarks do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/users/register", UserController, :register
    resources "/users", UserController do
      resources "/bookmarks", BookmarkController
    end


    resources "/sessions", SessionController, only: [:index ,:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Bookmarks do
  #   pipe_through :api
  # end
end

web/controllers/session_controller.ex
defmodule Bookmarks.SessionController do
  use Bookmarks.Web, :controller

  alias Bookmarks.AuthPlug, as: Auth
  alias Bookmarks.Repo

  def index(conn, _) do
    redirect conn, to: session_path(conn, :new)
  end

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session"=>%{"email"=>email, "password"=>pass}}) do
    case Auth.login_by_email_and_pass(conn, email, pass, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: page_path(conn, :index))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid email/password combo")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Auth.logout()
    |> redirect(to: page_path(conn, :index))
  end
end

web/views/session_view.ex
defmodule Bookmarks.SessionView do
  use Bookmarks.Web, :view
end

web/templates/session/new.html.eex
<center>
  <%= breadcrumbs do %>
    <%= breadcrumb nil, page_path(@conn, :index), icon: "home" %>
    <%= breadcrumb "Login", icon: "sign-in" %>
  <% end %>
</center>

<%= external_auth_links(@conn) %>

<%= or_div %>


<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email", class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= font_awesome_submit "Log In", "sign-in", icon_placement: "after", class: "btn btn-primary btn-block btn-lg" %>
<% end %>

<div class="center-sm reg-login-text" style="width: 175px;">
  <%= link "Don't have an account?", to: user_path(@conn, :register) %>
</div>