web/router.ex
defmodule Bookmarks.Router do
  use Bookmarks.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bookmarks.AuthPlug, repo: Bookmarks.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", Bookmarks do
    pipe_through :browser
    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end

  scope "/", Bookmarks do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/users/register", UserController, :register
    resources "/users", UserController do
      resources "/bookmarks", BookmarkController
    end


    resources "/sessions", SessionController, only: [:index ,:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Bookmarks do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Good Bookmarks" %></h2>
  <p class="lead">A bookmarking service</p>
</div>

<div class="row marketing">
  <center>
    <%= if @current_user do %>
      <%= font_awesome_link "View Your Bookmarks", "bookmark", to: user_bookmark_path(@conn, :index, @current_user.id),
        class: "btn btn-primary btn-lg" %>
    <% else %>
        <%= font_awesome_link "Sign up", "sign-in", to: "/users/register", class: "btn btn-success btn-lg" %>
        <%= or_div %>
        <%= font_awesome_link "Log in", "sign-in", to: session_path(@conn, :new), class: "btn btn-primary" %>
    <% end %>
</center>
</div>